/**
 * TypeScript 配置项 Schema 定义
 * 根据 TypeScript 官方文档定义所有配置项及其属性
 */

export interface ConfigOptionSchema {
  /** 配置项名称 */
  name: string
  /** 配置项中文名称 */
  nameZh?: string
  /** 配置项路径（支持嵌套，如 compilerOptions.target） */
  path: string
  /** 配置项类型 */
  type: 'string' | 'number' | 'boolean' | 'array' | 'object' | 'enum'
  /** 是否在 compilerOptions 中 */
  inCompilerOptions?: boolean
  /** 配置项分类 */
  category: string
  /** 默认值 */
  defaultValue?: any
  /** 类型说明 */
  description: string
  /** 中文描述 */
  descriptionZh: string
  /** 首次引入的 TypeScript 版本 */
  introducedIn?: string
  /** 废弃的 TypeScript 版本（如果已废弃） */
  deprecatedIn?: string
  /** 枚举值（如果是 enum 类型） */
  enumValues?: string[]
  /** 数组选项（如果是 array 类型，且选项固定） */
  arrayOptions?: string[]
  /** 示例值 */
  example?: any
}

/**
 * 配置项分类定义
 */
export const CONFIG_CATEGORIES = {
  LANGUAGE_ENV: 'language-env', // 语言和环境
  MODULES: 'modules', // 模块
  EMIT: 'emit', // 输出选项
  TYPE_CHECKING: 'type-checking', // 类型检查
  STRICTNESS: 'strictness', // 严格模式
  MODULE_RESOLUTION: 'module-resolution', // 模块解析
  INTEROP_CONSTRAINTS: 'interop-constraints', // 互操作性约束
  JAVASCRIPT_SUPPORT: 'javascript-support', // JavaScript 支持
  COMPLETENESS: 'completeness', // 完整性检查
  PROJECT_REFERENCES: 'project-references', // 项目引用
  OUTPUT_FORMATTING: 'output-formatting', // 输出格式
  EDITOR_SUPPORT: 'editor-support', // 编辑器支持
  ROOT_OPTIONS: 'root-options', // 根级别选项
} as const

/**
 * 分类显示名称
 */
export const CATEGORY_LABELS: Record<string, string> = {
  [CONFIG_CATEGORIES.LANGUAGE_ENV]: '语言和环境',
  [CONFIG_CATEGORIES.MODULES]: '模块',
  [CONFIG_CATEGORIES.EMIT]: '输出选项',
  [CONFIG_CATEGORIES.TYPE_CHECKING]: '类型检查',
  [CONFIG_CATEGORIES.STRICTNESS]: '严格模式',
  [CONFIG_CATEGORIES.MODULE_RESOLUTION]: '模块解析',
  [CONFIG_CATEGORIES.INTEROP_CONSTRAINTS]: '互操作性约束',
  [CONFIG_CATEGORIES.JAVASCRIPT_SUPPORT]: 'JavaScript 支持',
  [CONFIG_CATEGORIES.COMPLETENESS]: '完整性检查',
  [CONFIG_CATEGORIES.PROJECT_REFERENCES]: '项目引用',
  [CONFIG_CATEGORIES.OUTPUT_FORMATTING]: '输出格式',
  [CONFIG_CATEGORIES.EDITOR_SUPPORT]: '编辑器支持',
  [CONFIG_CATEGORIES.ROOT_OPTIONS]: '项目配置',
}

/**
 * 所有 TypeScript 配置项的完整定义
 */
export const TYPESCRIPT_CONFIG_SCHEMA: ConfigOptionSchema[] = [
  // ========== 语言和环境 ==========
  {
    name: 'target',
    nameZh: '编译目标',
    path: 'compilerOptions.target',
    type: 'enum',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.LANGUAGE_ENV,
    defaultValue: 'ES3',
    description: 'Set the JavaScript language version for emitted JavaScript',
    descriptionZh: '设置编译后的 JavaScript 版本',
    enumValues: ['ES3', 'ES5', 'ES6', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', 'ES2021', 'ES2022', 'ES2023', 'ESNext'],
  },
  {
    name: 'lib',
    nameZh: '库文件',
    path: 'compilerOptions.lib',
    type: 'array',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.LANGUAGE_ENV,
    defaultValue: [],
    description: 'Specify library files to be included in the compilation',
    descriptionZh: '指定要包含在编译中的库文件',
    arrayOptions: [
      'ES5', 'ES6', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', 'ES2021', 'ES2022', 'ES2023', 'ESNext',
      'DOM', 'DOM.Iterable', 'WebWorker', 'ScriptHost',
      'ES2015.Core', 'ES2015.Collection', 'ES2015.Generator', 'ES2015.Iterable', 'ES2015.Promise', 'ES2015.Proxy', 'ES2015.Reflect', 'ES2015.Symbol', 'ES2015.Symbol.WellKnown',
      'ES2016.Array.Include', 'ES2017.Object', 'ES2017.SharedMemory', 'ES2017.String', 'ES2017.TypedArrays', 'ES2018.AsyncIterable', 'ES2018.Promise', 'ES2018.Regexp',
      'ES2019.Array', 'ES2019.Object', 'ES2019.String', 'ES2019.Symbol',
      'ES2020.BigInt', 'ES2020.Promise', 'ES2020.String', 'ES2020.Symbol.WellKnown',
      'ES2021.Promise', 'ES2021.String', 'ES2021.WeakRef',
      'ES2022.Array', 'ES2022.Error', 'ES2022.Intl', 'ES2022.Object', 'ES2022.Regexp', 'ES2022.String',
      'ES2023.Array',
    ],
    example: ['ES2020', 'DOM', 'DOM.Iterable'],
  },
  {
    name: 'jsx',
    nameZh: 'JSX 模式',
    path: 'compilerOptions.jsx',
    type: 'enum',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.LANGUAGE_ENV,
    defaultValue: 'preserve',
    description: 'Specify JSX code generation',
    descriptionZh: '指定 JSX 代码生成',
    enumValues: ['preserve', 'react', 'react-native', 'react-jsx', 'react-jsxdev'],
  },
  {
    name: 'jsxFactory',
    nameZh: 'JSX 工厂函数',
    path: 'compilerOptions.jsxFactory',
    type: 'string',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.LANGUAGE_ENV,
    defaultValue: 'React.createElement',
    description: 'Specify the JSX factory function used when targeting React JSX emit',
    descriptionZh: '指定针对 React JSX 发出时使用的 JSX 工厂函数',
  },
  {
    name: 'jsxFragmentFactory',
    nameZh: 'JSX Fragment 工厂',
    path: 'compilerOptions.jsxFragmentFactory',
    type: 'string',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.LANGUAGE_ENV,
    description: 'Specify the JSX Fragment reference used for fragments when targeting react JSX emit',
    descriptionZh: '指定针对 React JSX 发出时用于片段的 JSX Fragment 引用',
  },
  {
    name: 'experimentalDecorators',
    nameZh: '实验性装饰器',
    path: 'compilerOptions.experimentalDecorators',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.LANGUAGE_ENV,
    defaultValue: false,
    description: 'Enable experimental support for decorators',
    descriptionZh: '启用装饰器的实验性支持',
  },
  {
    name: 'emitDecoratorMetadata',
    nameZh: '装饰器元数据',
    path: 'compilerOptions.emitDecoratorMetadata',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.LANGUAGE_ENV,
    defaultValue: false,
    description: 'Emit design-type metadata for decorated declarations in source files',
    descriptionZh: '为源文件中的装饰声明发出设计类型元数据',
  },
  {
    name: 'useDefineForClassFields',
    nameZh: '类字段定义方式',
    path: 'compilerOptions.useDefineForClassFields',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.LANGUAGE_ENV,
    defaultValue: true,
    description: 'Emit ECMAScript-standard-compliant class fields',
    descriptionZh: '发出符合 ECMAScript 标准的类字段',
    introducedIn: '3.7',
  },
  {
    name: 'downlevelIteration',
    nameZh: '降级迭代',
    path: 'compilerOptions.downlevelIteration',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.LANGUAGE_ENV,
    defaultValue: false,
    description: 'Emit more compliant, but verbose and less performant JavaScript for iteration',
    descriptionZh: '为迭代发出更合规但冗长且性能较低的 JavaScript',
  },

  // ========== 模块 ==========
  {
    name: 'module',
    nameZh: '模块系统',
    path: 'compilerOptions.module',
    type: 'enum',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.MODULES,
    defaultValue: 'CommonJS',
    description: 'Specify what module code is generated',
    descriptionZh: '指定生成什么模块代码',
    enumValues: ['None', 'CommonJS', 'AMD', 'System', 'UMD', 'ES6', 'ES2015', 'ES2020', 'ES2022', 'ESNext', 'Node16', 'NodeNext'],
  },
  {
    name: 'moduleResolution',
    nameZh: '模块解析策略',
    path: 'compilerOptions.moduleResolution',
    type: 'enum',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.MODULES,
    defaultValue: 'node',
    description: 'Specify how TypeScript looks up a file from a given module specifier',
    descriptionZh: '指定 TypeScript 如何从给定的模块说明符查找文件',
    enumValues: ['classic', 'node', 'node10', 'node16', 'nodenext', 'bundler'],
  },
  {
    name: 'resolveJsonModule',
    nameZh: '解析 JSON 模块',
    path: 'compilerOptions.resolveJsonModule',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.MODULES,
    defaultValue: false,
    description: 'Enable importing .json files',
    descriptionZh: '启用导入 .json 文件',
    introducedIn: '2.9',
  },
  {
    name: 'isolatedModules',
    nameZh: '隔离模块',
    path: 'compilerOptions.isolatedModules',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.MODULES,
    defaultValue: false,
    description: 'Ensure that each file can be safely transpiled without relying on other imports',
    descriptionZh: '确保每个文件都可以安全地转译，而不依赖于其他导入',
  },
  {
    name: 'verbatimModuleSyntax',
    nameZh: '逐字模块语法',
    path: 'compilerOptions.verbatimModuleSyntax',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.MODULES,
    defaultValue: false,
    description: 'Do not transform or elide any imports or exports',
    descriptionZh: '不转换或省略任何导入或导出',
    introducedIn: '5.0',
  },
  {
    name: 'allowImportingTsExtensions',
    nameZh: '允许导入 TS 扩展',
    path: 'compilerOptions.allowImportingTsExtensions',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.MODULES,
    defaultValue: false,
    description: 'Allow importing files with TypeScript extensions',
    descriptionZh: '允许导入带有 TypeScript 扩展名的文件',
    introducedIn: '4.7',
  },
  {
    name: 'importsNotUsedAsValues',
    nameZh: '未使用的导入值',
    path: 'compilerOptions.importsNotUsedAsValues',
    type: 'enum',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.MODULES,
    description: 'Specify emit/checking behavior for imports that are only used for types',
    descriptionZh: '指定仅用于类型的导入的发出/检查行为',
    enumValues: ['remove', 'preserve', 'error'],
    deprecatedIn: '5.0',
  },

  // ========== 输出选项 ==========
  {
    name: 'outDir',
    nameZh: '输出目录',
    path: 'compilerOptions.outDir',
    type: 'string',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.EMIT,
    description: 'Specify an output folder for all emitted files',
    descriptionZh: '指定所有输出文件的输出文件夹',
    example: './dist',
  },
  {
    name: 'outFile',
    nameZh: '输出文件',
    path: 'compilerOptions.outFile',
    type: 'string',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.EMIT,
    description: 'Specify a file that bundles all outputs into one JavaScript file',
    descriptionZh: '指定将所有输出打包成一个 JavaScript 文件',
  },
  {
    name: 'rootDir',
    nameZh: '根目录',
    path: 'compilerOptions.rootDir',
    type: 'string',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.EMIT,
    description: 'Specify the root folder within your source files',
    descriptionZh: '指定源文件的根文件夹',
    example: './src',
  },
  {
    name: 'declaration',
    nameZh: '生成声明文件',
    path: 'compilerOptions.declaration',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.EMIT,
    defaultValue: false,
    description: 'Generate .d.ts files from TypeScript and JavaScript files in your project',
    descriptionZh: '从项目中的 TypeScript 和 JavaScript 文件生成 .d.ts 文件',
  },
  {
    name: 'declarationMap',
    nameZh: '声明文件映射',
    path: 'compilerOptions.declarationMap',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.EMIT,
    defaultValue: false,
    description: 'Generate sourcemaps for d.ts files',
    descriptionZh: '为 .d.ts 文件生成 sourcemap',
  },
  {
    name: 'sourceMap',
    nameZh: 'Source Map',
    path: 'compilerOptions.sourceMap',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.EMIT,
    defaultValue: false,
    description: 'Generate source map files',
    descriptionZh: '生成 source map 文件',
  },
  {
    name: 'noEmit',
    nameZh: '不输出文件',
    path: 'compilerOptions.noEmit',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.EMIT,
    defaultValue: false,
    description: 'Disable emitting files from a compilation',
    descriptionZh: '禁用从编译中发出文件',
  },
  {
    name: 'emitDeclarationOnly',
    nameZh: '仅输出声明',
    path: 'compilerOptions.emitDeclarationOnly',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.EMIT,
    defaultValue: false,
    description: 'Only emit d.ts files and not JavaScript files',
    descriptionZh: '仅发出 .d.ts 文件而不发出 JavaScript 文件',
  },
  {
    name: 'removeComments',
    nameZh: '移除注释',
    path: 'compilerOptions.removeComments',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.EMIT,
    defaultValue: false,
    description: 'Disable emitting comments',
    descriptionZh: '禁用生成注释',
  },
  {
    name: 'importHelpers',
    nameZh: '导入辅助函数',
    path: 'compilerOptions.importHelpers',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.EMIT,
    defaultValue: false,
    description: 'Allow importing helper functions from tslib',
    descriptionZh: '允许从 tslib 导入辅助函数',
  },
  {
    name: 'noEmitHelpers',
    nameZh: '不输出辅助函数',
    path: 'compilerOptions.noEmitHelpers',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.EMIT,
    defaultValue: false,
    description: 'Disable generating custom helper functions',
    descriptionZh: '禁用生成自定义辅助函数',
  },
  {
    name: 'noEmitOnError',
    nameZh: '错误时不输出',
    path: 'compilerOptions.noEmitOnError',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.EMIT,
    defaultValue: false,
    description: 'Disable emitting files if any type checking errors are reported',
    descriptionZh: '如果报告了任何类型检查错误，则禁用发出文件',
  },
  {
    name: 'preserveConstEnums',
    nameZh: '保留常量枚举',
    path: 'compilerOptions.preserveConstEnums',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.EMIT,
    defaultValue: false,
    description: 'Do not erase const enum declarations in generated code',
    descriptionZh: '不要在生成的代码中擦除 const enum 声明',
  },
  {
    name: 'incremental',
    nameZh: '增量编译',
    path: 'compilerOptions.incremental',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.EMIT,
    defaultValue: false,
    description: 'Save .tsbuildinfo files to allow for incremental compilation of projects',
    descriptionZh: '保存 .tsbuildinfo 文件以允许项目的增量编译',
    introducedIn: '3.4',
  },
  {
    name: 'tsBuildInfoFile',
    nameZh: '构建信息文件',
    path: 'compilerOptions.tsBuildInfoFile',
    type: 'string',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.EMIT,
    description: 'Specify the path to .tsbuildinfo incremental compilation file',
    descriptionZh: '指定 .tsbuildinfo 增量编译文件的路径',
    introducedIn: '3.4',
  },

  // ========== 类型检查 ==========
  {
    name: 'noImplicitAny',
    nameZh: '禁止隐式 Any',
    path: 'compilerOptions.noImplicitAny',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.TYPE_CHECKING,
    defaultValue: false,
    description: 'Enable error reporting for expressions and declarations with an implied any type',
    descriptionZh: '为具有隐式 any 类型的表达式和声明启用错误报告',
  },
  {
    name: 'strictNullChecks',
    nameZh: '严格空值检查',
    path: 'compilerOptions.strictNullChecks',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.TYPE_CHECKING,
    defaultValue: false,
    description: 'When type checking, take into account null and undefined',
    descriptionZh: '类型检查时考虑 null 和 undefined',
  },
  {
    name: 'strictFunctionTypes',
    nameZh: '严格函数类型',
    path: 'compilerOptions.strictFunctionTypes',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.TYPE_CHECKING,
    defaultValue: false,
    description: 'When assigning functions, check to ensure parameters and the return values are subtype-compatible',
    descriptionZh: '分配函数时，检查以确保参数和返回值是子类型兼容的',
  },
  {
    name: 'strictBindCallApply',
    nameZh: '严格绑定调用应用',
    path: 'compilerOptions.strictBindCallApply',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.TYPE_CHECKING,
    defaultValue: false,
    description: 'Check that the arguments for bind, call, and apply methods match the original function',
    descriptionZh: '检查 bind、call 和 apply 方法的参数是否匹配原始函数',
  },
  {
    name: 'strictPropertyInitialization',
    nameZh: '严格属性初始化',
    path: 'compilerOptions.strictPropertyInitialization',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.TYPE_CHECKING,
    defaultValue: false,
    description: 'Check for class properties that are declared but not set in the constructor',
    descriptionZh: '检查类属性是否已声明但未在构造函数中设置',
  },
  {
    name: 'noImplicitThis',
    nameZh: '禁止隐式 This',
    path: 'compilerOptions.noImplicitThis',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.TYPE_CHECKING,
    defaultValue: false,
    description: 'Enable error reporting when this is given the type any',
    descriptionZh: '当 this 被赋予 any 类型时启用错误报告',
  },
  {
    name: 'noUncheckedIndexedAccess',
    nameZh: '未检查索引访问',
    path: 'compilerOptions.noUncheckedIndexedAccess',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.TYPE_CHECKING,
    defaultValue: false,
    description: 'Add undefined to a type when accessed using an index',
    descriptionZh: '使用索引访问时向类型添加 undefined',
    introducedIn: '4.1',
  },
  {
    name: 'noImplicitOverride',
    nameZh: '禁止隐式覆盖',
    path: 'compilerOptions.noImplicitOverride',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.TYPE_CHECKING,
    defaultValue: false,
    description: 'Ensure overriding members in derived classes are marked with override modifier',
    descriptionZh: '确保派生类中的重写成员使用 override 修饰符标记',
    introducedIn: '4.3',
  },
  {
    name: 'exactOptionalPropertyTypes',
    nameZh: '精确可选属性类型',
    path: 'compilerOptions.exactOptionalPropertyTypes',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.TYPE_CHECKING,
    defaultValue: false,
    description: 'Differentiate between undefined and not present when type checking',
    descriptionZh: '类型检查时区分 undefined 和不存在',
    introducedIn: '4.4',
  },
  {
    name: 'noPropertyAccessFromIndexSignature',
    nameZh: '禁止索引签名属性访问',
    path: 'compilerOptions.noPropertyAccessFromIndexSignature',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.TYPE_CHECKING,
    defaultValue: false,
    description: 'Enforces using indexed accessors for keys declared using an indexed type',
    descriptionZh: '强制对使用索引类型声明的键使用索引访问器',
    introducedIn: '4.2',
  },
  {
    name: 'noImplicitReturns',
    nameZh: '禁止隐式返回',
    path: 'compilerOptions.noImplicitReturns',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.TYPE_CHECKING,
    defaultValue: false,
    description: 'Enable error reporting for codepaths that do not explicitly return in a function',
    descriptionZh: '为函数中未显式返回的代码路径启用错误报告',
  },
  {
    name: 'noFallthroughCasesInSwitch',
    nameZh: '禁止 Switch 穿透',
    path: 'compilerOptions.noFallthroughCasesInSwitch',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.TYPE_CHECKING,
    defaultValue: false,
    description: 'Enable error reporting for fallthrough cases in switch statements',
    descriptionZh: '为 switch 语句中的 fallthrough 情况启用错误报告',
  },
  {
    name: 'noUnusedLocals',
    nameZh: '禁止未使用的局部变量',
    path: 'compilerOptions.noUnusedLocals',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.TYPE_CHECKING,
    defaultValue: false,
    description: 'Enable error reporting when a local variables arent read',
    descriptionZh: '启用错误报告当局部变量未被读取时',
  },
  {
    name: 'noUnusedParameters',
    nameZh: '禁止未使用的参数',
    path: 'compilerOptions.noUnusedParameters',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.TYPE_CHECKING,
    defaultValue: false,
    description: 'Raise an error when a function parameter isnt read',
    descriptionZh: '当函数参数未被读取时引发错误',
  },
  {
    name: 'allowUnusedLabels',
    nameZh: '允许未使用的标签',
    path: 'compilerOptions.allowUnusedLabels',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.TYPE_CHECKING,
    defaultValue: false,
    description: 'Disable error reporting for unused labels',
    descriptionZh: '禁用未使用标签的错误报告',
    introducedIn: '4.2',
  },
  {
    name: 'allowUnreachableCode',
    nameZh: '允许不可达代码',
    path: 'compilerOptions.allowUnreachableCode',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.TYPE_CHECKING,
    defaultValue: true,
    description: 'Disable error reporting for unreachable code',
    descriptionZh: '禁用不可达代码的错误报告',
  },
  {
    name: 'suppressExcessPropertyErrors',
    nameZh: '抑制多余属性错误',
    path: 'compilerOptions.suppressExcessPropertyErrors',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.TYPE_CHECKING,
    defaultValue: false,
    description: 'Disable reporting of excess property errors during the creation of object literals',
    descriptionZh: '在创建对象字面量期间禁用报告多余属性错误',
  },
  {
    name: 'suppressImplicitAnyIndexErrors',
    nameZh: '抑制隐式 Any 索引错误',
    path: 'compilerOptions.suppressImplicitAnyIndexErrors',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.TYPE_CHECKING,
    defaultValue: false,
    description: 'Suppress noImplicitAny errors when indexing objects lacking index signatures',
    descriptionZh: '在索引缺少索引签名的对象时抑制 noImplicitAny 错误',
  },
  {
    name: 'noStrictGenericChecks',
    nameZh: '非严格泛型检查',
    path: 'compilerOptions.noStrictGenericChecks',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.TYPE_CHECKING,
    defaultValue: false,
    description: 'Disable strict checking of generic signatures in function types',
    descriptionZh: '禁用函数类型中泛型签名的严格检查',
  },
  {
    name: 'keyofStringsOnly',
    nameZh: 'Keyof 仅字符串',
    path: 'compilerOptions.keyofStringsOnly',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.TYPE_CHECKING,
    defaultValue: false,
    description: 'Make keyof only return strings instead of string | number',
    descriptionZh: '使 keyof 仅返回字符串而不是 string | number',
    deprecatedIn: '4.0',
  },

  // ========== 严格模式 ==========
  {
    name: 'strict',
    nameZh: '严格模式',
    path: 'compilerOptions.strict',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.STRICTNESS,
    defaultValue: false,
    description: 'Enable all strict type-checking options',
    descriptionZh: '启用所有严格类型检查选项',
  },
  {
    name: 'alwaysStrict',
    nameZh: '始终严格',
    path: 'compilerOptions.alwaysStrict',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.STRICTNESS,
    defaultValue: false,
    description: 'Ensure use strict is always emitted',
    descriptionZh: '确保始终发出 use strict',
  },

  // ========== 模块解析 ==========
  {
    name: 'baseUrl',
    nameZh: '基础 URL',
    path: 'compilerOptions.baseUrl',
    type: 'string',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.MODULE_RESOLUTION,
    description: 'Specify the base directory to resolve non-relative module names',
    descriptionZh: '指定解析非相对模块名称的基本目录',
    example: './',
  },
  {
    name: 'paths',
    nameZh: '路径映射',
    path: 'compilerOptions.paths',
    type: 'object',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.MODULE_RESOLUTION,
    description: 'Specify a set of entries that re-map imports to additional lookup locations',
    descriptionZh: '指定一组将导入重新映射到其他查找位置的条目',
    example: { '@/*': ['src/*'] },
  },
  {
    name: 'rootDirs',
    nameZh: '根目录列表',
    path: 'compilerOptions.rootDirs',
    type: 'array',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.MODULE_RESOLUTION,
    description: 'Allow multiple root folders to be combined',
    descriptionZh: '允许组合多个根文件夹',
    example: ['src', 'tests'],
  },
  {
    name: 'typeRoots',
    nameZh: '类型根目录',
    path: 'compilerOptions.typeRoots',
    type: 'array',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.MODULE_RESOLUTION,
    description: 'Specify multiple folders that act like ./node_modules/@types',
    descriptionZh: '指定多个像 ./node_modules/@types 一样工作的文件夹',
    example: ['./typings', './other-typings'],
  },
  {
    name: 'types',
    nameZh: '类型包',
    path: 'compilerOptions.types',
    type: 'array',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.MODULE_RESOLUTION,
    description: 'Specify type package names to be included',
    descriptionZh: '指定要包含的类型包名称',
    example: ['node', 'jest'],
  },
  {
    name: 'preserveSymlinks',
    nameZh: '保留符号链接',
    path: 'compilerOptions.preserveSymlinks',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.MODULE_RESOLUTION,
    defaultValue: false,
    description: 'Disable resolving symlinks to their realpath',
    descriptionZh: '禁用将符号链接解析为其真实路径',
  },
  {
    name: 'noResolve',
    nameZh: '不解析',
    path: 'compilerOptions.noResolve',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.MODULE_RESOLUTION,
    defaultValue: false,
    description: 'Disable resolving files from imports',
    descriptionZh: '禁用从导入解析文件',
  },

  // ========== 互操作性约束 ==========
  {
    name: 'esModuleInterop',
    nameZh: 'ES 模块互操作',
    path: 'compilerOptions.esModuleInterop',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.INTEROP_CONSTRAINTS,
    defaultValue: false,
    description: 'Emit additional JavaScript to ease support for importing CommonJS modules',
    descriptionZh: '发出额外的 JavaScript 以简化对导入 CommonJS 模块的支持',
  },
  {
    name: 'allowSyntheticDefaultImports',
    nameZh: '允许合成默认导入',
    path: 'compilerOptions.allowSyntheticDefaultImports',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.INTEROP_CONSTRAINTS,
    defaultValue: false,
    description: 'Allow default imports from modules with no default export',
    descriptionZh: '允许从没有默认导出的模块进行默认导入',
  },
  {
    name: 'forceConsistentCasingInFileNames',
    nameZh: '强制文件名大小写一致',
    path: 'compilerOptions.forceConsistentCasingInFileNames',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.INTEROP_CONSTRAINTS,
    defaultValue: false,
    description: 'Ensure that casing is correct in imports',
    descriptionZh: '确保导入中的大小写正确',
  },

  // ========== JavaScript 支持 ==========
  {
    name: 'allowJs',
    nameZh: '允许 JavaScript',
    path: 'compilerOptions.allowJs',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.JAVASCRIPT_SUPPORT,
    defaultValue: false,
    description: 'Allow JavaScript files to be a part of your program',
    descriptionZh: '允许 JavaScript 文件成为程序的一部分',
  },
  {
    name: 'checkJs',
    nameZh: '检查 JavaScript',
    path: 'compilerOptions.checkJs',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.JAVASCRIPT_SUPPORT,
    defaultValue: false,
    description: 'Enable error reporting in type-checked JavaScript files',
    descriptionZh: '在类型检查的 JavaScript 文件中启用错误报告',
  },
  {
    name: 'maxNodeModuleJsDepth',
    nameZh: 'Node 模块 JS 最大深度',
    path: 'compilerOptions.maxNodeModuleJsDepth',
    type: 'number',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.JAVASCRIPT_SUPPORT,
    defaultValue: 0,
    description: 'Specify the maximum folder depth used for checking JavaScript files from node_modules',
    descriptionZh: '指定用于检查 node_modules 中 JavaScript 文件的最大文件夹深度',
  },
  {
    name: 'skipLibCheck',
    nameZh: '跳过库检查',
    path: 'compilerOptions.skipLibCheck',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.JAVASCRIPT_SUPPORT,
    defaultValue: false,
    description: 'Skip type checking all .d.ts files',
    descriptionZh: '跳过所有 .d.ts 文件的类型检查',
  },
  {
    name: 'skipDefaultLibCheck',
    nameZh: '跳过默认库检查',
    path: 'compilerOptions.skipDefaultLibCheck',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.JAVASCRIPT_SUPPORT,
    defaultValue: false,
    description: 'Skip type checking .d.ts files that are included with TypeScript',
    descriptionZh: '跳过 TypeScript 包含的 .d.ts 文件的类型检查',
  },


  // ========== 项目引用 ==========
  {
    name: 'composite',
    nameZh: '复合项目',
    path: 'compilerOptions.composite',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.PROJECT_REFERENCES,
    defaultValue: false,
    description: 'Enable constraints that allow a TypeScript project to be used with project references',
    descriptionZh: '启用约束，允许 TypeScript 项目与项目引用一起使用',
    introducedIn: '3.0',
  },
  {
    name: 'assumeChangesOnlyAffectDirectDependencies',
    nameZh: '假设变更仅影响直接依赖',
    path: 'compilerOptions.assumeChangesOnlyAffectDirectDependencies',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.PROJECT_REFERENCES,
    defaultValue: false,
    description: 'Have recompiles in projects that use incremental and watch mode assume that changes within a file will only affect files directly depending on it',
    descriptionZh: '在使用增量和监视模式的项目中，重新编译假设文件内的更改只会影响直接依赖它的文件',
    introducedIn: '3.8',
  },

  // ========== 输出格式 ==========
  {
    name: 'pretty',
    nameZh: '美化输出',
    path: 'compilerOptions.pretty',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.OUTPUT_FORMATTING,
    defaultValue: true,
    description: 'Enable color and formatting in TypeScript output',
    descriptionZh: '在 TypeScript 输出中启用颜色和格式',
  },
  {
    name: 'newLine',
    nameZh: '换行符',
    path: 'compilerOptions.newLine',
    type: 'enum',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.OUTPUT_FORMATTING,
    description: 'Set the newline character for emitting files',
    descriptionZh: '设置发出文件的新行字符',
    enumValues: ['crlf', 'lf'],
  },
  {
    name: 'charset',
    nameZh: '字符集',
    path: 'compilerOptions.charset',
    type: 'string',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.OUTPUT_FORMATTING,
    description: 'Specify the character set of the input files',
    descriptionZh: '指定输入文件的字符集',
    deprecatedIn: '4.0',
  },
  {
    name: 'locale',
    nameZh: '区域设置',
    path: 'compilerOptions.locale',
    type: 'string',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.OUTPUT_FORMATTING,
    description: 'Specify the locale used for error messages',
    descriptionZh: '指定用于错误消息的区域设置',
  },

  // ========== 编辑器支持 ==========
  {
    name: 'plugins',
    nameZh: '插件',
    path: 'compilerOptions.plugins',
    type: 'array',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.EDITOR_SUPPORT,
    description: 'Specify a list of language service plugins',
    descriptionZh: '指定语言服务插件列表',
    introducedIn: '2.3',
  },
  {
    name: 'watchOptions',
    nameZh: '监视选项',
    path: 'compilerOptions.watchOptions',
    type: 'object',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.EDITOR_SUPPORT,
    description: 'Specify options for watching files',
    descriptionZh: '指定监视文件的选项',
    introducedIn: '3.8',
  },
  {
    name: 'watchDirectory',
    nameZh: '监视目录',
    path: 'compilerOptions.watchDirectory',
    type: 'enum',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.EDITOR_SUPPORT,
    description: 'Specify how directories are watched',
    descriptionZh: '指定如何监视目录',
    enumValues: ['useFsEvents', 'fixedPollingInterval', 'dynamicPriorityPolling', 'fixedChunkSizePolling'],
    introducedIn: '3.8',
  },
  {
    name: 'watchFile',
    nameZh: '监视文件',
    path: 'compilerOptions.watchFile',
    type: 'enum',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.EDITOR_SUPPORT,
    description: 'Specify how individual files are watched',
    descriptionZh: '指定如何监视单个文件',
    enumValues: ['fixedPollingInterval', 'priorityPollingInterval', 'dynamicPriorityPolling', 'useFsEvents', 'useFsEventsOnParentDirectory'],
    introducedIn: '3.8',
  },
  {
    name: 'preserveWatchOutput',
    nameZh: '保留监视输出',
    path: 'compilerOptions.preserveWatchOutput',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.EDITOR_SUPPORT,
    defaultValue: false,
    description: 'Disable wiping the console in watch mode',
    descriptionZh: '在监视模式下禁用清除控制台',
  },
  {
    name: 'traceResolution',
    nameZh: '跟踪解析',
    path: 'compilerOptions.traceResolution',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.EDITOR_SUPPORT,
    defaultValue: false,
    description: 'Enable tracing of the name resolution process',
    descriptionZh: '启用名称解析过程的跟踪',
  },
  {
    name: 'listFiles',
    nameZh: '列出文件',
    path: 'compilerOptions.listFiles',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.EDITOR_SUPPORT,
    defaultValue: false,
    description: 'Print names of files part of the compilation',
    descriptionZh: '打印编译中包含的文件名称',
  },
  {
    name: 'listEmittedFiles',
    nameZh: '列出输出文件',
    path: 'compilerOptions.listEmittedFiles',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.EDITOR_SUPPORT,
    defaultValue: false,
    description: 'Print names of generated files part of the compilation',
    descriptionZh: '打印编译中生成的文件的名称',
  },
  {
    name: 'diagnostics',
    nameZh: '诊断信息',
    path: 'compilerOptions.diagnostics',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.EDITOR_SUPPORT,
    defaultValue: false,
    description: 'Show diagnostic information',
    descriptionZh: '显示诊断信息',
  },
  {
    name: 'extendedDiagnostics',
    nameZh: '扩展诊断',
    path: 'compilerOptions.extendedDiagnostics',
    type: 'boolean',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.EDITOR_SUPPORT,
    defaultValue: false,
    description: 'Show verbose diagnostic information',
    descriptionZh: '显示详细的诊断信息',
  },
  {
    name: 'generateCpuProfile',
    nameZh: '生成 CPU 性能分析',
    path: 'compilerOptions.generateCpuProfile',
    type: 'string',
    inCompilerOptions: true,
    category: CONFIG_CATEGORIES.EDITOR_SUPPORT,
    description: 'Generate a CPU profile',
    descriptionZh: '生成 CPU 配置文件',
  },

  // ========== 根级别选项 ==========
  {
    name: 'include',
    nameZh: '包含文件',
    path: 'include',
    type: 'array',
    inCompilerOptions: false,
    category: CONFIG_CATEGORIES.ROOT_OPTIONS,
    defaultValue: [],
    description: 'Specify an array of glob patterns that match a set of source files',
    descriptionZh: '指定匹配一组源文件的 glob 模式数组',
    example: ['src/**/*'],
  },
  {
    name: 'exclude',
    nameZh: '排除文件',
    path: 'exclude',
    type: 'array',
    inCompilerOptions: false,
    category: CONFIG_CATEGORIES.ROOT_OPTIONS,
    defaultValue: ['node_modules'],
    description: 'Specify an array of glob patterns that match a set of source files to exclude',
    descriptionZh: '指定要排除的一组源文件的 glob 模式数组',
    example: ['node_modules', 'dist'],
  },
  {
    name: 'extends',
    nameZh: '继承配置',
    path: 'extends',
    type: 'string',
    inCompilerOptions: false,
    category: CONFIG_CATEGORIES.ROOT_OPTIONS,
    description: 'Specify another tsconfig.json file to inherit configuration from',
    descriptionZh: '指定要继承配置的另一个 tsconfig.json 文件',
    example: './base.json',
  },
  {
    name: 'files',
    nameZh: '文件列表',
    path: 'files',
    type: 'array',
    inCompilerOptions: false,
    category: CONFIG_CATEGORIES.ROOT_OPTIONS,
    description: 'Specify an array of files to include',
    descriptionZh: '指定要包含的文件数组',
    example: ['./src/index.ts'],
  },
  {
    name: 'references',
    nameZh: '项目引用',
    path: 'references',
    type: 'array',
    inCompilerOptions: false,
    category: CONFIG_CATEGORIES.ROOT_OPTIONS,
    description: 'Specify an array of project references',
    descriptionZh: '指定项目引用数组',
    introducedIn: '3.0',
  },
]
